### ISSUE TITLE
`use_read` panics at runtime as it unwraps empty val

### ISSUE THREAD

**Issue by t1m0t** [DioxusLabs/fermi#2]
The docs didn't mention to init the `AtomRoot` with `use_init_atom_root` as already stated in the tests.

**Comment by t1m0t** [comment]
In the future, either we need to encourage the react provider pattern where you wrap your app in context providers, or allow hooks to automatically inject a provider into any scope that they choose (with most choosing ScopeId(0)) if a parent doesn't exist.

_Originally posted by @jkelleyrtp in https://github.com/DioxusLabs/fermi/issues/3#issuecomment-1016573436_

**Comment by jkelleyrtp** [comment]
I've opened a PR at https://github.com/DioxusLabs/dioxus/pull/139 which allows the "default provider" pattern. I need to write a few more tests but that will allow the usage of libraries like Fermi without the need to "use_init_root" since the any child can inject a default into the root scope if it doesn't already exist.
